### ISSUE TITLE
default camera focal/aperture ?

### ISSUE THREAD

**Issue by lulu1315** [TadasBaltrusaitis/OpenFace#116]
hello
I'm trying to export all results into a 3D package.so far so good for all the values.
but what about the (default) camera settings.
is it orthographic or perspective ?
what focal/aperture value should I use ?
optical center is obviously in the middle of the frame I guess.
thanks for insights.
luc

**Comment by TadasBaltrusaitis** [comment]
Dear Luc,

The head pose estimation is done with the assumption of a perspective camera, for focal lengths you should use the actual parameters of the camera which can be found out by using a camera calibration procedure (http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html, specifically look at fx, fy, cx, cy parameters) or looking them up online as there are some resources listing them (within a certain error range as there will be slight differences due to manufacturing variability).

If you do not specify the parameters, the code assumes a "standard" webcam and guesstimates the parameters. While not perfect this works reasonably well in practice.

Thanks,
Tadas

**Comment by lulu1315** [comment]
hello Tadas
thanks for the answer.
let say my camera has a focal length of 30 mm and a sensor size of 23.76 x 13.37 mm (1.778 ratio)
the picture has 1280x720 pixels
I assume the optical center is at the center of the frame and no distorsion ..

it work if I calculate the focal length in pixels : 
f = 1280*30/23.76 = 1616.16

I first thought fy=fx/1.778 but finally it works if fx=fy

thanks a lot.
luc

**Comment by TadasBaltrusaitis** [comment]
Yes the optical center is most often the center of the frame if there is no major distortion.

Your estimates look about right, just a small note:
`fx = 1280*30/23.76=1616.16`
`fy = 720*30/13.37=1615.55`

But with such small differences you can set both of them to the same value.

Thanks,
Tadas
