### ISSUE TITLE
Why align the model to a Multi-PIE one when we train PDM model?

### ISSUE THREAD

**Issue by xiaoxiongli** [TadasBaltrusaitis/OpenFace#136]
Dear @TadasBaltrusaitis, 

Now I try to train a face "PDM model" with fewer landmarks (totally 18 landmarks).

But I find some code to align the model to a Multi-PIE one in the file "Create_pdm_wild.m":

**Also align the model to a Multi-PIE one for accurate head orientation
% also align the mean shape model (an aligned 68 point PDM from Multi-PIE dataset)**

I feel confused that:
1. Why should we align the model to a Multi-PIE one?
2. If I do Not need the head pose, Can i ignore and comment it during training?

thank you ^_^

**Comment by TadasBaltrusaitis** [comment]
Hi,

The reason I align it to a Multi-PIE model is because there is no restriction from the Non-rigid structure from motion about what counts as a frontal/upwards face, the resulting PDM could be of a tilted or rotated face. The Multi-PIE model is manually rotated to be frontal, and using it as a common reference point allows me to align it in a way that mean face of a resulting model is a frontal one and the model can then be used for head pose estimation.

If you do not care about head pose you can ignore that part. However, you might still want to rotate the model to the mean shape of the landmark points as for landmark detection you want to initialize to the mean face shape and not a rotated one. 

In general, I would advise you visualize the PDM and its modes of variation when it is created as the non-rigid structure from motion is sensitive to the parameters used and may need some tweaking to get a good model out of it.

Thanks,
Tadas

**Comment by xiaoxiongli** [comment]
Dear TadasBaltrusaitis,  i got it, thank you very much! ^_^
