### ISSUE TITLE
How can i generate such "bounding_boxes_xxx.mat" by myself?

### ISSUE THREAD

**Issue by xiaoxiongli** [TadasBaltrusaitis/OpenFace#145]
Dear @TadasBaltrusaitis,

When i try to train the face validator, i find that we need load "matlab_version\bounding_box_mapping\bounding_boxes_afw.mat". 

i wonder that How to generate such "bounding_boxes_xxx.mat" by myself?  As you know, sometimes maybe we want to use other face landmark database(such like 300w's XM2VTS).

thank you very much~ ^_^

**Comment by TadasBaltrusaitis** [comment]
Hi,

Do you mean training a bounding box correction model? The face validator code is in `matlab_version\face_validation`, and I don't think it uses that file. 

In order to find a mapping from the bounding box of your face detector to an ideal one, you need to find the ideal bounding box (around the minimum and maximum values of the actual landmark locations) and the bounding box from a face detector of interest. That is what is stored in the `bounding_boxes_afw.mat` file.

Thanks,
Tadas

**Comment by xiaoxiongli** [comment]
dear Tadas, in  this file  matlab_version/face_validation/Test_face_checker.m we need that mat file to test the validator. 

 the function Collect_wild_imgs will be called，and then Collect_AFW()，in this function we will load this bounding_boxes_afw.mat. 

anyway，i will generate it since you already give me the tips about the contents inside.

thank you very much～
