### ISSUE TITLE
Unable to modify size of output images using 'feature_extraction_demo_img_seq.m'

### ISSUE THREAD

**Issue by sidk2496** [TadasBaltrusaitis/OpenFace#163]
Hello,
I am looking to align the faces from LFW dataset using this toolbox.
I am using the 'feature_extraction_demo_img_seq.m' in 'matlab_runners' folder to achieve this. 

The dos command I am passing is as follows:- "../../x64/Release/FeatureExtraction.exe" -verbose -asvid -fdir "C:\Users\siddharth2496\Downloads\lfw-20170331T102901Z-001\lfw\AJ_Cook" -of "./lfw/AJ_Cook/AJ_Cook.txt" -simscale 0.9 -simsize  224  -simalign "./lfw/AJ_Cook/AJ_Cook" -hogalign "./lfw/AJ_Cook/AJ_Cook.hog" 

While all the arguments work fine, the simsize and simscale parameters don't seem to work for me. The aligned output image is always created with the default size of 112x112 and scale 0.7. Please correct me if I am mistaken in the dos command. Any leads in this regard will be of great help.

Thanks

**Comment by TadasBaltrusaitis** [comment]
Hi,

Which version of OpenFace are you using? The earlier version did not have the fix for feature extraction size, but the newest version does (you will need to compile it though).

Also if you are extracting features from images that are not part of a video sequence you should not use the `-asvid` flag.

Thanks,
Tadas

**Comment by sidk2496** [comment]
Thank You, I guess it's the older version. I'll try recompiling the new version.
