### ISSUE TITLE
How to Response Map initialize ?

### ISSUE THREAD

**Issue by dedoogong** [TadasBaltrusaitis/OpenFace#198]
I'm reviewing LandmarkDetectorModel.cpp to handle the way of initializing Response Maps generated by patch experts. I guess there should be 68 response maps corresponding each 68 landmarks.

Assuming that I have a 5 landmarks(corresponding to R/L eyes, Nose, R/L mouth tips) which can be considered ground truth and I want to initialize the 5 landmarks to the corresponding CLNF's response maps.

I found there are some init related parts such as "init()" in LandmarkDetectorParameters.cpp and 5 initial multiview Euler angle vectors.

Thank you!

Seunghyun Lee.

**Comment by TadasBaltrusaitis** [comment]
Hi,

You are right that there will be 68 response maps corresponding to each of the landmarks (with fewer landmarks for profile faces due to self-occlusion).

To initialize the response maps using ground truth locations you would need to edit the actual response maps computed by the following function:
`patch_experts.Response(patch_expert_responses, sim_ref_to_img, sim_img_to_ref, im, depth_img_no_background, pdm, params_global, params_local, window_size, scale);`

In the `LandmarkDetectorModel.cpp` file, but you will need to think about what form the initialization take and also where the high density peak should be in it (as the response map is in it's own reference frame)

Thanks,
Tadas
