### ISSUE TITLE
How can I obtain the output data of multiple individuals in a single video(i.e. a classroom) when I execute multi face detection?

### ISSUE THREAD

**Issue by lingminlingminlingmin** [TadasBaltrusaitis/OpenFace#210]
Hi Tadas

Firstly, I as a graduate student in the field of psychology, I am very grateful and thankful for the face detection application you have created and continue to constantly improve. As mentioned in the title, I am unsure how I can obtain the output data when I run the program.
For example, I understand how to use feature_extraction to obtain one person's data (i.e. gaze and pose). I have used the multi face detection program, and the detection is successful but it doesn't seem to output each individual's data. Am I reading the data wrong? Can you please tell me how to solve this problem?

Sincerely,
Min Ling

**Comment by TadasBaltrusaitis** [comment]
Hi Min Ling,

Currently OpenFace only supports output from one person using `FeatureExtraction`. The multi face tracker `FaceLandmarkVidMulti` only performs face tracking and does not output anything. 

The reason for this is that in order to perform successful multi-face output the code would need to be able to re-identify each person so that an output file would always correspond to the same person. This is especially important for AU detection which performs per-person adaptation. While it would be possible to extend `FaceLandmarkVidMulti` to have the functionality you need it is not trivial and would require quite a bit of coding and I am not planning on adding this feature soon.

A *hacky* way to solve this problem is by cropping the video into several videos with only one person present in each and then running `FeatureExtraction` on them.

Thanks,
Tadas

**Comment by TadasBaltrusaitis** [comment]
This support has been added now. It is still experimental however.
