### ISSUE TITLE
What is the unit of focal lengths ?

### ISSUE THREAD

**Issue by jojotof** [TadasBaltrusaitis/OpenFace#25]
Hi

I don't understand how to set the focal lengths.

I have a Logitech C930e with a FOV of 90° and is 16/9.
Searching a bit it seems that HFOV is ~52° and VFOV is ~82°.
Not easy to find more info about the specs but i could find that the big brother C920 as a focal length of 3.67 mm

Values in the code are about 500 (mm ?) (based on 640*480 résolution) so I realy don't understand what is the unit and how to compte the value.

Thank you

**Comment by TadasBaltrusaitis** [comment]
Hi,

The focal length expected by OpenFace is in pixels (rather than millimeters). To compute it from the focal length in mm use the following:
f_px = f_mm * (sensor_size_px / sensor_size_mm)

So the f_px is linearly related to the camera resolution. It seems you found the f_mm already and you just need to find the sensor size of the camera. 

Another option is to use a OpenCV camera calibration functionality to perform the calibration manually - http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html

Thanks,
Tadas

**Comment by jojotof** [comment]
Thanks for your reply.
Christophe
