### ISSUE TITLE
Is there any way to deal with multiple faces in one scene?

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#313]
Is there any way to deal with multiple faces in one scene?
Possible option or at least mark that there was multiple face was detected in the scene (frame).

I am extracting the faces from several clips, but I found openface selects random face and extract it during command-line approach.

Bests,
J.

**Comment by TadasBaltrusaitis** [comment]
At the moment only individual image processing (`FaceLandmarkImg`) supports multiple faces, the reason for this is because OpenFace has no way to tell if it is the same face across frames, also assuming that there is only one face in the frame makes some processing faster.

**Comment by iPsych** [comment]
Is there any advantage/disadvantage to using individual image processing? 
(i.e. the detection rate of AU.)
If there is no significant difference, I will try frame-by-frame image processing too.

**Comment by TadasBaltrusaitis** [comment]
There is a disadvantage in using individual image processing. Because sequence processing can assume that the same person appears in the video it can perform person specific calibration increasing the accuracy of a number of AUs. That is one of the reasons why sequence processing does not handle multiple faces as that makes person specific calibration more difficult.

**Comment by TadasBaltrusaitis** [comment]
Multiple face support for videos has been added, but it is still experimental and AU prediction will not be as accurate.

**Comment by tissotrv** [comment]
How to run multiple face video analysis?

**Comment by TadasBaltrusaitis** [comment]
You can use FaceLandmarkVidMulti executable
