### ISSUE TITLE
Wiki not correct eyes numbers

### ISSUE THREAD

**Issue by palich12** [TadasBaltrusaitis/OpenFace#325]
Little trouble in wiki

> Gaze related
> gaze_0_x, gaze_0_y, gaze_0_z Eye gaze direction vector in world coordinates for eye 0 (normalized)
> gaze_1_x, gaze_1_y, gaze_1_z Eye gaze direction vector in world coordinates for eye 0 (normalized)

Can you replace zeros to left eye and right eye?

**Comment by TadasBaltrusaitis** [comment]
Hi,

I used 0 and 1 instead of left or right on purpose, as left and right, could be ambiguous depending if it means in an image or persons left or right, also sometimes in webcam feeds the image might be mirrored leading to more confusion. Eye 0 is the eye that is leftmost in the image, eye 1 is the rightmost eye. I updated the wiki accordingly
