### ISSUE TITLE
Some questions about the model training！

### ISSUE THREAD

**Issue by MoreyLiu** [TadasBaltrusaitis/OpenFace#334]
Dear Tadas:
First off, Thanks to your such surprising project!
I want to use openface for face detection in near-infrared images, but the effect is not as stable as conventional images. When the posture of the head returns to normal from a large angle, the test results sometimes go wrong (eyebrows are wrongly detected as eyes) I guess this may be due to the fact that the facial grayscales of near-infrared images are different from the regular images. I want to train patch_expert separately for different parts. Where should I need to modify when I follow your training code. Hope to get your advice.
In addition, would you please tell me which matlab program generated the pdm_28_l_eye.mat and pdm_l_eye.mat, and I didn't find their training code.
Hope to get your reply!
Best regards!

Morey Liu,
SuZhou,China.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Yes there are sometimes big differences between NIR and visible light images, especially around the eye region. Retraining the model might be your best bet, in order to do that follow instructions:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-Training

Most of the instructions should be there, but if anything is missing, please let me know as the documentation is still a work in progress.

I never got around to packaging the PDM generation and patch training for the eye region models, however, the code would be very similar to the code here:
`matlab_version\pdm_generation\Wild_data_pdm\Create_pdm_mouth.m`

Thanks,
Tadas
