### ISSUE TITLE
Heart/pulse rate from video

### ISSUE THREAD

**Issue by luke777** [TadasBaltrusaitis/OpenFace#373]
I read that there have been some attempts to estimate heart/pulse rate from video by detecting small changes in skin color or small heading movements.  I was curious whether this could be achieved using similar approaches to those used by Openface.  I appreciate that the existing examples are likely the outcome of years of research rather than something that could be easily implemented.

**Comment by TadasBaltrusaitis** [comment]
You're right that there's a body of work exploring heart/pulse rate from video. While OpenFace does not have such functionality (and the methods used for pulse rate analysis are quite different), it could definitely help you in locating the areas of the face/skin to analyze.

**Comment by ChrizzyM87** [comment]
A really basic attempt to do this is taking the alignedFace image from OpenFace; calc. the mean of the green channel (because signal is stronger their compared to the other channels) for every frame and e.G. buffer these values, so you get a timetrace. After that you can perform a FFT on that timetrace, detect the highest peak in the spectrum and take this as your heart rate. Easy but not very robust :-)
