### ISSUE TITLE
how to run under unix

### ISSUE THREAD

**Issue by MLey89** [TadasBaltrusaitis/OpenFace#410]
Hello!

Im trying to run your project under ubuntu, but im not quite sure how to use your scripts properly. i installed with the install.sh script but am unable to analyze videos with the return message: "FaceLandmarkVid: Command not found.". Right now im installing the whole thing anew. Also is there a way to access the GUI under ubuntu just like with the windows executables?

also have you thought of a way to log emotional states? There are so many parameters exported in the csv by default and i am trying to find a way to first timesynchronize the data (i guess that depends on the FPS of my webcam and i just have to divide the amount of measurements with that and have a timespan in seconds) and then have a column for emotions at certain times, but i guess i have to think of my own method based on the landmarks.

Greetings Matthias

**Comment by TadasBaltrusaitis** [comment]
Hi Matthias,

Can you check the build/bin directory to see if FaceLandmarkVid exists? Did the builds succeed? 

You can always try performing the build manually rather than through the install script (see https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation)

Unfortunately, only the Windows version contains the GUI, as it is based on Windows Presentation Foundation which is only available on Windows.

For logging, just using fps and timestamps from OpenFace might not be enough as they are subject to drift. If everything is being recorded on the same machine you could use the date time of the machine to synchronize (you would need to change OpenFace to record that instead of the timestamp it currently records).

Thanks,
Tadas

**Comment by MLey89** [comment]
Hi Tadas,

Thanks for your reply! I tried running the install script manually, but when trying to make the OpenFace build i get the following error:

CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TBB (missing: TBB_ROOT_DIR TBB_INCLUDE_DIR TBB_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindTBB.cmake:291 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:34 (find_package)

also there is no directory FaceLandMarkVid in my build folder, just a bunch of other folders and files.

However - if i cant get the script to run under unix, it doesnt concern us too much, but what troubles us more is that we are not sure if we can somehow classify emotions based on the data we get from your tool. Can you tell us how the markers for the facial landmarks are named? If that works, we probably could write a script in matlab and analyze our videos that way, by setting tresholds and for example say if the markers from the corner of the mouth exceeds a certain point and other landmarks show some other behaviour too we might classify the time-window as happy or sad.

Its a workaround but i am really not skilled in the whole deep learning and facial recognition thematic, so what do you think?

Best regards,
Matthias
