### ISSUE TITLE
Extension FaceAnalyserManaged class possible?

### ISSUE THREAD

**Issue by Arkansadave** [TadasBaltrusaitis/OpenFace#419]
Hi,

Is it possible and are there plans that the FaceAnalyserManaged class would be extended with a getcurrentemotion function which will return a probability that an emotion is present? I know its possible to deduct this from the presence of AU's (from FACS)

Best regards

**Comment by TadasBaltrusaitis** [comment]
Not in the near future. While mapping from FACS to a set of prototypical expressions of emotions is possible it is not very accurate. Further, perception of expressions of emotion is very subjective and context dependent and often requires extra sources of information for interpretation rather than just videos or images. For these reasons I chose not to include them into OpenFace.
