### ISSUE TITLE
OpenFace 2.0 x86 build

### ISSUE THREAD

**Issue by palich12** [TadasBaltrusaitis/OpenFace#446]
I have problem with run x64 bulid. May be it heppen because I'm setup vc_redist.x86.exe and I can't reinstall vc_redist.x64.exe. So I need x86 build for correct run OpenFace 2. Can you add x86 build to last release?

**Comment by TadasBaltrusaitis** [comment]
I don't think that different VC redistributables clash, at least I have not experienced it myself. What is the exact problem with the x64 build you are experiencing?

The reason why x86 build is not included yet is because of the memory issues it has in multiple face tracking case that I have not had the chance to resolve yet. The new version will come with a x86 build.

**Comment by palich12** [comment]
> What is the exact problem with the x64 build you are experiencing
It's crash if vc_redist.x86.exe already installed.

> The new version will come with a x86 build.
Great, can you say approx date of new release?

**Comment by TadasBaltrusaitis** [comment]
That's really odd, are you sure the issue is to do with vc_redist and not just a crash because of something else?

I am planning to release the update by the end of the week.

**Comment by palich12** [comment]
> That's really odd, are you sure the issue is to do with vc_redist and not just a crash because of something else?
Not sure, beacose i install many libraryes on my work PC, but fact, that only x86 work for me. So if new release so fast, it solve my problem 👍

**Comment by TadasBaltrusaitis** [comment]
I added an x86 version to the new release.
