### ISSUE TITLE
How to know x_n, and y_n for 2d Landmarks

### ISSUE THREAD

**Issue by fxfactorial** [TadasBaltrusaitis/OpenFace#467]
Wiki says:

```

After landmark detection is done face_model stores the landmark locations and local and global Point Distribution Model parameters inferred from the image. To access them and more use:

2D landmark location (in image):

face_model.detected_landmarks contains a double matrix in following format [x1;x2;...xn;y1;y2...yn] describing the detected landmark locations in the image
```

but not seeing in code where the number of x_n is or y_n. How do I know how many xis, yis, there are?

**Comment by TadasBaltrusaitis** [comment]
It is 68 by default, but you can get it by calling:
`face_model.pdm.NumberOfPoints()`

**Comment by fxfactorial** [comment]
Is there a meaning to 68 or just number picked?

**Comment by TadasBaltrusaitis** [comment]
It is a fairly common set of landmarks used by the community, it includes points that are possible to annotate for humans (the annotations are required for training the landmark detectors). 

However, there are also datasets that have fewer or more landmarks, and the choice of landmarks is sometimes arbitrary rather than scientific.
