### ISSUE TITLE
Creating 3D face modelling to improve accuracy?

### ISSUE THREAD

**Issue by Bilabong67** [TadasBaltrusaitis/OpenFace#477]
Hi Tadas,
I have noticed that AU prediction is less accurate when the person's face is not perfectly frontal.
Do you think it would make sense to have the algorithm build a 3D reconstruction of the face to improve AU prediction even with rotated faces?
Many thanks

**Comment by TadasBaltrusaitis** [comment]
Hi,

Yes, AU detection is definitely affected by the orientation of the face. This is due to the fact that most of the training data consists of frontal images. 

Some form of 3D modeling could be helpful and there are a number of approaches that could be taken, e.g. if you have 3D scans of people (and some of the datasets do), you can always render images of what the faces would look like at different orientations and use that as training data. Or you could use the orientation data during training so that the method learns to compensate (e.g. lowering the head makes the prediction think that the brow is lowered, but this could be counteracted). What exactly did you have in mind?

**Comment by federicoparra** [comment]
Hi Tadas, how about this? https://github.com/fengju514/Expression-Net
