### ISSUE TITLE
Eye and Eyebrow landmarking on a partial face image

### ISSUE THREAD

**Issue by kivancguckiran** [TadasBaltrusaitis/OpenFace#496]
Hello and thanks for the awesome library.

I'm having trouble locating only eye and eyebrow landmarks in a partial face image.

After building, I use the FaceLandmarkImg executable. I've added both image and the command.

`./FaceLandmarkImg -f partial.jpg`

![partial.jpg](https://user-images.githubusercontent.com/9072047/41963845-3fcd9c3c-7a01-11e8-9327-7187162e1761.jpg)

This command does not detect any features. I've tried with proper faces, and I know it is working normally.

I think, I probably don't need a face detection and locating the other facial landmarks, since I will use only partial face images for my project, but I couldn't figure out a way.

Thanks for any advance!

**Comment by TadasBaltrusaitis** [comment]
Hi,

OpenFace currently does not support only partial face landmark detection. This is because it relies on face detection to initialize landmark detection, and a partial image like you posted will result in a failure in face detection.

It could be possible to detect eyes and initialize landmark detection from that, but this would require reasonably significant amount of new code.

**Comment by kivancguckiran** [comment]
Hi again!

Thanks for the answer. I've been thinking about this. Is there any way to detect only eye and eyebrows location, without detecting the face and other parts? I'm new to this area, and I'm open to suggestion. I'm up to use OpenFace but if you can direct me to somewhere, I'd be happy to oblige.

Hope it's alright to ask/post this. I'm closing this issue since I guess there is not any future milestone for this.

Thanks!
