### ISSUE TITLE
Emotions

### ISSUE THREAD

**Issue by eradisch** [TadasBaltrusaitis/OpenFace#535]
Hey!
First of all, I want to express, that I am realy like the tool, you have created! It is amazing how good it works!

I wondered, if you already tried to read basic emotions like a smile or so from the AUs? I am not sure, if I understood it right, but as far as I understood wikipedia (https://en.wikipedia.org/wiki/Facial_Action_Coding_System), then I just have to add the value of several AUs, to get basic emotions. Is that right? Or do I have to considere something else?

Sincerely,

Erik

**Comment by TadasBaltrusaitis** [comment]
Hi,

The reason OpenFace does not predict basic emotions from AUs, is because the mapping is not as straightforward as the wikipedia article would suggest. Expression of emotion is very context specific and the same expression could mean a lot of different things depending on the situation/culture/age/etc. of the person showing it. Further, the dynamics of the expression matter a lot (e.g. a quick smile might mean something very different from a slow one).

While, it is possible to make a simple mapping, it will often be unreliable.

Thanks,
Tadas
