### ISSUE TITLE
how to adapt the validator to different landmark number?

### ISSUE THREAD

**Issue by zhao181** [TadasBaltrusaitis/OpenFace#550]
dear author,
what should we do to the validator_cnn_68.txt if a small number of landmarks are used? is there a relevent paper or training code?  looking forward to your reply.

**Comment by TadasBaltrusaitis** [comment]
Hi,

A validator can be trained for different set of landmarks as well. You can find the code for validator training here - https://github.com/TadasBaltrusaitis/OpenFace/tree/master/matlab_version/face_validation

The current validator isn't described in detail in any paper, but an earlier version is described in my thesis (same idea but using a Support Vector Machine instead of a Convolutional Neural Network) - https://www.cl.cam.ac.uk/~tb346/pub/thesis/phd_thesis.pdf, section 4.6.2
