### ISSUE TITLE
the landmarks of lower lip offset upward when i open  mouth fast during tracking

### ISSUE THREAD

**Issue by msewindy** [TadasBaltrusaitis/OpenFace#552]
hi, Tadas
I transplant  the project in android.
The locations of  lower lip landmarks are not accurate when i open mouth  fast.
but  vs 2015 project has not this problem.

i think the prolem is relative with the FPS, as in vs 2015 the FPS is 20+ on PC,  but FPS is 10~13 on my android phone.

then  do you have any proposal ?
thanks  a lot.
![openmouth](https://user-images.githubusercontent.com/42334601/44015979-a072e168-9f05-11e8-99c3-30d243bd7bbb.png)

**Comment by TadasBaltrusaitis** [comment]
It is likely that the problem is the relative FPS of the methods. The method relies on a form of tracking where the landmarks in current frame are searched next to the landmarks detected in previous frame, if the face moves less from frame to frame the algorithm has a better chance of coping with the motion. 

There are several options you could try:
1. Optimize the method to run faster
2. Increasing the search space of landmarks around the mouth area (although I have not tried that and don't know if it would work).
3. Performing some form of optical flow tracking to initialize landmarks better
4. Restarting the tracking every n frames or when you think the mouth moved fast, sometimes resetting tracking detects open mouth correctly
