### ISSUE TITLE
is it necessary that align the pdm model  to  a Multi-PIE one for accurate head orientation ? 

### ISSUE THREAD

**Issue by msewindy** [TadasBaltrusaitis/OpenFace#563]
Hi,Tadas,
in the train pdm model code , the pdm model will align to  a Multi-PIE one for accurate head orientation.
i want to train some more landmarks. but the PDM_multi-pie model is 68 points.
i can not find the PDM_multi-pie model trainning code in the folder './model_trainning'.
so if i remove the align step , will the landmark detection result be very bad?
thanks.

**Comment by TadasBaltrusaitis** [comment]
Hi,

The PDM Multi-PIE model was manually aligned to make sure that the face is frontal in the mean shape (this is not enforced by model training). I use it to align the other PDM models to ensure that head orientation reported by OpenFace makes sense. The landmark detection should still be good without this alignment step, because the mean shape constructed in PDM training should be close to frontal (unless there's a lot of bias in your training data). 

The PDM you construct does not have to have the same points as the Multi-PIE one in order to align it though, as long as there is some overlap between the points. You can manually specify the points that overlap.

**Comment by Harry-675** [comment]
HI，
I trained a 106 landmarks model, which can't be aligned to the multi-pie model, what should I do?

**Comment by TadasBaltrusaitis** [comment]
If you want accurate head pose you need to make sure the "mean shape" is of a frontal head. 

There's no requirement about using the multi-pie model, I just found it helpful to align to it first, as it was manually ensured that it is forward facing. Even if you have 106 landmarks, do none of them align with the 66 in the multi-pie model? You can define the subset of them that do and then align them to the Multi-PIE model.

**Comment by Harry-675** [comment]
@TadasBaltrusaitis 
Thanks a lot.
I think I'd better align it to a 106 landmarks model, do you know any  of them?

**Comment by TadasBaltrusaitis** [comment]
Sorry, I'm not sure I understood your question? Do I know a 106 landmark model? You can always try aligning the face to an existing 3D face model, such as Candide or Basel face model.
