### ISSUE TITLE
head rotation on OpenFaceOffline.exe are different from right flip to left

### ISSUE THREAD

**Issue by darkkyrie** [TadasBaltrusaitis/OpenFace#576]
**Describe the bug**
i just flipped a image, and the turn value shows on OpenFaceOffline.exe should be the same but some how it's not, is there some options i need to set? (in some tests the different is larger)

![image](https://user-images.githubusercontent.com/20471343/46201744-7baf9900-c347-11e8-8db9-27930c2068e3.png)
![image](https://user-images.githubusercontent.com/20471343/46201849-c4675200-c347-11e8-984c-5f908ee73416.png)

**To Reproduce**
Steps to reproduce the behavior, with error description (and images/videos if failing on them).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Compiler [if compilation or linker error]

**Additional context**

**Comment by TadasBaltrusaitis** [comment]
There are several reasons why it might not be identical, face detector we are using does not enforce symmetry, so a mirrored image will not provide the same mirrored face detection. Further the landmark detectors themselves do not enforce symmetry (while to save computation cost some of them are mirrored versions of each other, there are others that will not work in a symmetrized way). Finally the point distribution model is also not symmetric.

All of this is because of certain biases in the training data, that leads to results not being identical for flipped images.
