### ISSUE TITLE
the difference for binary and VS code

### ISSUE THREAD

**Issue by haimingZZ** [TadasBaltrusaitis/OpenFace#59]
Hi,
OpenFace is an excellent framework and I am fascinated about the outstanding result. I have been using this frameworks for weeks and it's awesome.

However, I noticed that there is a little difference for the binary result and the vs code .

I download the OpenFace v0.1 from your webpage (Windows Executable (older Windows executable, for those who cannot wait)). The tracking result and landmarks detected for both video camera and videos are super stable.

I download the VS program following from GitHub page(both 0.1 0.2 version) and run the same video clip. The landmarks are not that stable. I did another test to draw the landmarks using the position saved from Windows executable, it's not stable either.

After that test, I record the landmark positions from Windows executable and VS program. I found that the numbers are not the same. I wonder if there is a difference between the windows executable and vs program. 

And is there any tips on how to stabilize the landmarks for input video ?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

Thanks for letting me know. I think the problem is because of slightly different models used, the newer version attempts to use a hierarchical model in addition to regular one possibly resulting in them *pulling* in different directions resulting in the jitter. The hierarchical version is indeed better for images but might not result in better tracks for videos, I will investigate this for the next version. As a quick fix try removing the second line in the:
`main_clnf_general.txt` file that is being loaded by the executable, the line is:
`LandmarkDetector_part model_inner/main_clnf_inner.txt inner 17 0 18 1 19 2 20 3 21 4 22 5 23 6 24 7 25 8 26 9 27 10 28 11 29 12 30 13 31 14 32 15 33 16 34 17 35 18 36 19 37 20 38 21 39 22 40 23 41 24 42 25 43 26 44 27 45 28 46 29 47 30 48 31 49 32 50 33 51 34 52 35 53 36 54 37 55 38 56 39 57 40 58 41 59 42 60 43 61 44 62 45 63 46 64 47 65 48 66 49 67 50 17 0 18 1 19 2 20 3 21 4 22 5 23 6 24 7 25 8 26 9 27 10 28 11 29 12 30 13 31 14 32 15 33 16 34 17 35 18 36 19 37 20 38 21 39 22 40 23 41 24 42 25 43 26 44 27 45 28 46 29 47 30 48 31 49 32 50 33 51 34 52 35 53 36 54 37 55 38 56 39 57 40 58 41 59 42 60 43 61 44 62 45 63 46 64 47 65 48 66 49 67 50`

Let me know if that addresses the issue.

Thanks,
Tadas

**Comment by haimingZZ** [comment]
Thanks for the advice.

I removed the line in main_clnf_general.txt. The result actually get better for video. However, it's not as stable as the landmarks shown in Windows Executable 0.1. 

Is there any advice/tips on how to avoid the jitters in the video?  I tried to add the post-processing process to smooth the pulling in different directions. It didn't work well. Therefore, i think maybe i train the CLNF model and do some change will help. Is there any suggestions on how to modify the training process of CLNF to avoid the jitters?

Thanks a lot.

Haiming

**Comment by TadasBaltrusaitis** [comment]
I will be exploring this in the next version of the code in the coming weeks, will let you know if I manage to address the issue. I do not know if new training will help resolve the problem though, as the model is trained on images.

Another quick fix is removing the eye modules in the hierarchical model (if you don't care about gaze tracking).

Thanks,
Tadas

**Comment by haimingZZ** [comment]
Thanks for your suggestion.

I will do some tests to avoid jitters. If further result is satisfying, i will let you know.

Thanks again.

Haiming

**Comment by TadasBaltrusaitis** [comment]
I added one fix to reduce the jitter (thanks Jinzhan Su). The problem was partly not the tracking but its visualization, the tracking itself would be smooth but the drawing would jitter a lot as integer coordinates were used instead of floating point ones. This has been addressed, I will also investigate the issue with the hierarchical model as well for the future versions.

**Comment by haimingZZ** [comment]
Great! 
This version is super stable.
Thanks again
.
Haiming
