### ISSUE TITLE
Issue while generating OpenFace_vs2017.snl

### ISSUE THREAD

**Issue by YannFavin95** [TadasBaltrusaitis/OpenFace#616]
Hi,

First thank you for all your work and releasing it on GitHub!

I'm looking for installing OpenFace on windows 10 x64 for a school project. I'm running on visual studio 2017 but when i try to generate OpenFace_vs2017, i got the following error messages:

Error LNK1104	: impossible to open the file 'opencv_world340.lib'	

Error CS0006 :  'C:\Users\yannf\OneDrive\Documents\Projet Facial Recognition Stroke Patients\OpenFace-master\x64\Debug\CppInerop.dll' file not found

I am new to all this stuff so i may have done things wrong. Have you an idea of what i might have done wrong or how to solve my problem?

Thank you very much and have a nice day!

**Comment by TadasBaltrusaitis** [comment]
Can you try building in Release mode? Does that produce the same error?

**Comment by dhhunter** [comment]
In Visual Studio 2017 the $(PlatformToolset) is v141 instead of v140

So
%(AdditionalLibraryDirectories)

Which is defined as:
$(SolutionDir)lib\3rdParty\OpenCV3.4\$(PlatformTarget)\$(PlatformToolset)\lib\$(Configuration)
$(SolutionDir)lib\3rdParty\boost\$(PlatformTarget)\$(PlatformToolset)\lib

Is no longer valid.

That said, I have been unable to determine where %(AdditionalLibraryDirectories) is actually defined.

There is also an %(AdditionalDependencies)

That specifies: libboost_filesystem-vc$(PlatformToolsetVersion)-mt-1_63.lib which is also no longer correct.

**Comment by TadasBaltrusaitis** [comment]
What do you mean by generating the visual studio 2017 project? You should just open the one that is prepared and not upgrade it to VS2017, as the libraries for OpenCV etc. were build on Visual Studio 15.

**Comment by TadasBaltrusaitis** [comment]
VS2017 is the main .sln now.
