### ISSUE TITLE
Question) In study for Openface

### ISSUE THREAD

**Issue by yj7679** [TadasBaltrusaitis/OpenFace#623]
Hi, Tadas. i'm studying about Cursor control program for brain lesion patients with Openface.
Currently, Mouse cursor in windows os and ubuntu can be controlled through the direction of the eye.
Furthermore, I want to do a study that the mouse cursor moves to the position where the patient is looking.
I think the system can be built Through machine learning with openface's result values.
But I wonder if I can. Can this be done? Please advise me. Thank you.

**Comment by TadasBaltrusaitis** [comment]
Hi,

I'm not sure if OpenFace is accurate enough for precise cursor control (it's only accurate enough to tell the side of the screen rather than exact object the person is focusing on). From my understanding, to get good enough quality to control cursors you need specialist eye tracking equipment (e.g. something like - https://tobiigaming.com/products/) 

Thanks,
Tadas
