### ISSUE TITLE
The error MSB307

### ISSUE THREAD

**Issue by KentLin1** [TadasBaltrusaitis/OpenFace#629]
I run the code on Windows use VS17
There are 5 errors
error MSB3073	command“xcopy /I /E /Y /D /C "E:\OpenFace-master\lib\3rdParty\tbb\bin\x64\v141\tbb_debug.dll" "E:\OpenFace-master\x64\Debug\"
:VCEnd”.
I dont know how to solve it.

**Comment by smartel99** [comment]
I just had this error as well, turns out that there is no folder `v141` in the `x64` folder. You need to change the path in the Pre-Build Event Command line option of the project so that instead of the PlatformToolset macro the path contains the name of the folder that is there.

Here's an example (on my system) because I feel like my explication is extremely confusing xD
(I am using MSVC2019)
Here's the error message:
```MSB3073	The command "xcopy /I /E /Y /D /C "D:\dev\OpenFace-master\lib\3rdParty\tbb\bin\x64\v142\tbb.dll" "D:\dev\OpenFace-master\x64\Release\"
:VCEnd" exited with code 4.
```

Inside `D:\dev\OpenFace-master\lib\3rdParty\tbb\bin\x64`, there's only one folder: `v140`, no `v142` as the path is trying to find.

Going in the Pre-Build Event tab (Project settings -> Build Events -> Pre-Build Event), we see that the command that fails is
```
xcopy /I /E /Y /D /C "$(SolutionDir)lib\3rdParty\tbb\bin\$(PlatformShortName)\$(PlatformToolset)\tbb.dll" "$(OutDir)"
```
By examining this path, we find that the `v142` folder in the path comes from `$(PlatformToolset)`. To fix the error, simply change `$(PlatformToolset)` by the name of the folder, `v140` in my case

**Comment by TadasBaltrusaitis** [comment]
I will be soon moving the entire project to VS2017, so this should not be an issue anymore in the new version.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed in the new version.
