### ISSUE TITLE
OpenFace landmark detection vs dlib

### ISSUE THREAD

**Issue by capilano** [TadasBaltrusaitis/OpenFace#651]
Do you have any comparison metrics vs the 68 point dlib facial landmarks? Thanks

**Comment by ArmainAP** [comment]
I think OpenFace is based on dlib's 68 point facial landmarks.

**Comment by capilano** [comment]
Ah! Forgot I left a question here. I think OpenFace uses dlib for the bounding boxes and they have their own landmark detector because they cite a few papers on their landing page at Github specifically pertaining to facial landmarks .

**Comment by TadasBaltrusaitis** [comment]
While OpenFace has a dlib dependency the method for landmark detection is quite different and I believe significantly more accurate (I have conducted a number of experiments, but don't have numbers at hand comparing to dlib directly, for most recent results see the OpenFace 2.0 paper - https://www.dropbox.com/s/ki1inrjcjbwm24j/FG2018_camera_ready.pdf?dl=0). While dlib landmark detector is good it relies on a somewhat older method which has been superceded with more modern landmark detection approaches.

The use of dlib is for face detection and HOG extraction rather than for landmark detection.

**Comment by capilano** [comment]
@TadasBaltrusaitis Thanks. I have implementing a CNN based facial detector for my application, which is far superior to dlib (in terms of accuracy).
