### ISSUE TITLE
Eye Landmark Registration

### ISSUE THREAD

**Issue by karanahujax** [TadasBaltrusaitis/OpenFace#7]
Is it possible to detect eye and/or iris landmarks, given only the image of the eye as follows:
![image](https://cloud.githubusercontent.com/assets/9433038/15448441/7f726c7a-1f7f-11e6-95f7-b8395e26fb34.png)
or a much more cropped eye image:
![image](https://cloud.githubusercontent.com/assets/9433038/15448445/9a0fde0a-1f7f-11e6-9034-e696a3ad8f30.png)

If so, could you please provide a pseudo-code on how to do so given any such image.

Image taken from http://efdreams.com/data_images/dreams/face/face-03.jpg.

**Comment by TadasBaltrusaitis** [comment]
There is no built in way to do so directly. 

We do have a pre-trained eye landmark detector, [see](http://www.errollw.com/publications/iccv2015.pdf) (especially Figure 10), it is currently being used in a hierarchical fashion with the full 68 facial landmarks. In order to use it directly you would need to:
1. first detect the eye region (using an eye detector say from OpenCV)
2. Initialize the eye specific landmark detector (as is done from face detection now, and might require some region correction to provide a tight bounding box around the landmarks of interest)
3. Perform the fitting using the eye region landmark detector

This all will require some work, but it is possible to build an eye region landmark detection for the eyelids and the iris using OpenFace.

Of course this is all easier if you have the full face image and just use the code as it is, you would just need to get the landmark detections from the hierarchical model which are not being written out out the moment.

**Comment by karanahujax** [comment]
Thanks for a quick reply!
I have now got the eye region (using opencv haarcascade for eyes), which pdm should I use to detect the eye landmarks and subsequently iris?

**Comment by TadasBaltrusaitis** [comment]
Depending on which eye you are doing (left or right) use the model (PDM and patch experts) in the following file:
`model/model_eye/main_clnf_synth_left.txt` or `model/model_eye/main_clnf_synth_right.txt`

To intitialize the model from the bounding box you will need to call:
'clnf_model.pdm.CalcParams(clnf_model.params_global, bounding_box, clnf_model.params_local)'

For the actual detection:

Be aware that the bounding box from haarcascade might not be as tight as that expected by the model and might need to be resized. An ideal bounding box should be `[minX, minY, maxX, maxY]` of the landmarks.

**Comment by sarratouil** [comment]
@TadasBaltrusaitis  I need to detect the iris of eyes  in real time like this
![iris](https://user-images.githubusercontent.com/34163796/56676218-1db91900-66be-11e9-91f5-6a35b7b6f094.jpg)

can you help me

**Comment by TadasBaltrusaitis** [comment]
OpenFace already detects most of those landmarks (except for the eyelid crease 16-24) in real time if the entirety of the face is visible. Have a look at - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format, especially `eye_lmk_` outputs.

**Comment by cpatrickalves** [comment]
> @TadasBaltrusaitis I need to detect the iris of eyes in real time like this
> ![iris](https://user-images.githubusercontent.com/34163796/56676218-1db91900-66be-11e9-91f5-6a35b7b6f094.jpg)
> 
> can you help me

Hello sarratouil, 

Can you tell me which solution do you use to get all these points? 
I need to get the eyelid crease 16-24

Thanks in advance

**Comment by raquel-gutierrez** [comment]
> Hello @cpatrickalves,
 
Did you find the code to do the detection of only the eye ?

Thanks in advance

**Comment by cpatrickalves** [comment]
> > Hello @cpatrickalves,
> 
> Did you find the code to do the detection of only the eye ?
> 
> Thanks in advance

No, I didn't.

**Comment by raquel-gutierrez** [comment]
And do you have something similar ?

**Comment by cpatrickalves** [comment]
> And do you have something similar? 


Unfortunately no.
