### ISSUE TITLE
Why the landmark point looks stable when drawing with 'draw_shiftbits' parameter？

### ISSUE THREAD

**Issue by SiZuo** [TadasBaltrusaitis/OpenFace#707]
After getting the landmark points, I draw the landmark points with `circle` function in opencv without `shift` parameter. And I found that with `shift=0` , the landmark points drawing on the image jitter obviously. 

Why the code choose to draw the landmark points with 'shift' parameter? And why the parameter. the points look more stable on the image?

**Comment by TadasBaltrusaitis** [comment]
This is because without the `shift` parameter OpenCV cannot draw points with sub-pixel accuracy. So for example if a landmark is detected at `~(10.5, 12)` location in a video it might jump between being drawn around `~(10, 12)` or `~(11, 12)` instead of being drawn in the middle. Using the `shift` parameter allows for such an offset when drawing. Hope this answers your question.

**Comment by SiZuo** [comment]
Yes it helps a lot. Thanks.
