### ISSUE TITLE
openface matlab MTCNN implementation question

### ISSUE THREAD

**Issue by btuan** [TadasBaltrusaitis/OpenFace#825]
Hi! After reading #510 I was digging into your implementation of MTCNN a bit more.
It seems like your implementation may have rearranged the network slightly -- let me know if I'm mistaken here.

For example, your PNet has these layers:
conv -> prelu -> pool -> conv -> prelu -> conv -> prelu -> fc -> softmax
https://github.com/TadasBaltrusaitis/OpenFace/blob/master/matlab_version/face_detection/mtcnn/PNet.m#L6-L21

While the original MTCNN authors has this architecture for their PNet:
conv -> prelu -> pool -> conv -> prelu -> conv -> prelu -> conv -> conv -> softmax
https://github.com/kpzhang93/MTCNN_face_detection_alignment/blob/master/code/codes/MTCNNv1/model/det1.prototxt

Can you shed some light on why your implementation replaces the latter two conv layers with a fully-connected layer, etc.?

**Comment by TadasBaltrusaitis** [comment]
I don't remember why I did that exactly, I believe I made sure that the outputs from both the original and my implementation would be the same.

One reason may be that any convolutional layer can be implemented as a fully connected layer, and in case of 1x1 convolutions there's not much of an optimization from doing convolution instead of a fully connected version, so I think I may have replaced the two convolutions with FC (also they can be combined to one layer as there's no non-linear operation in between)

**Comment by btuan** [comment]
Hey Tadas, thanks for the clarification!
