### ISSUE TITLE
Testing on an Augmented BP4D dataset.

### ISSUE THREAD

**Issue by khaleelyo** [TadasBaltrusaitis/OpenFace#874]
- Since BP4D offers 3D meshes for its recording, it is then possible to manipulate the 3D planes and produce novel datasets.

- Openface relied on BP4D in its training, which brings us to the question:  **Is it possible to use Openface in evaluating AUs on an augmented BP4D data set without bias?**

**Comment by TadasBaltrusaitis** [comment]
Sorry I'm not entirely sure about your question, there seem to be two questions here?

> Since BP4D offers 3D meshes for its recording, it is then possible to manipulate the 3D planes and produce novel datasets.

I believe so, in the past I've generated datasets from BP4D for landmark detection training (this is not used in OpenFace though). I imagine it would be possible to build more reliable recognition of AUs across pose using such an approach.

> Openface relied on BP4D in its training, which brings us to the question: Is it possible to use Openface in evaluating AUs on an augmented BP4D data set without bias?

In an ideal world we should probably always evaluate across datasets to try minimizing bias (but even then bias might remain, e.g. due to biased demographics etc.). However, often it is impossible to do due to limited availability of public datasets, so next best thing is to do person independent evaluation and making sure that training/validation/test sets do not contain the same subject.

**Comment by khaleelyo** [comment]
Thank you for the comprehensive reply. 
I agree, the question format might have been a bit confusing.

-  The 1st point was just illustrating how augmented data sets can be derived from the original BP4D. 

- The 2nd point questioned the result validity, if such derived BP4D data sets we're tested through OpenFace's pipeline; which had previous exposure (specifically HOGs and PCA) to the original BP4D date set.
