### ISSUE TITLE
What is the world coordinate?

### ISSUE THREAD

**Issue by kbawyg** [TadasBaltrusaitis/OpenFace#89]
I have noted that the gaze tracking result obtained by OpenFace is in world coordinate. What is the world coordinate?

**Comment by ArtSebus** [comment]
+1 
I have this question for pose estimation. Also to add to it, how can we convert world coordinate to display coordinate.

**Comment by TadasBaltrusaitis** [comment]
It is a simple Cartesian Coordinate System (https://en.wikipedia.org/wiki/Cartesian_coordinate_system), with the camera acting as the origin at `(0,0,0)`. Representing orientation is slightly more difficult, it is describe as 3 Euler angles (pitch, yaw, and roll) that can be converted to a `3x3` rotation matrix.

The function `visualise_tracking` shows how these results can be used to draw on the screen, look specifically at `Draw`, `DrawBox`, and `DrawGaze` functions.

**Comment by ArtSebus** [comment]
Could someone provide a short a description on how `DrawBox` works. I am having a bit of difficulties understanding how the box is drawn around the face

**Comment by TadasBaltrusaitis** [comment]
It uses 3D location of the head to determine a 3D bounding box around it (in millimeters in world coordinate space, with the camera at the origin `0,0,0`). It then uses camera parameters (focal length and optical axis) to project those 3D coordinates to 2D ones in image space (http://faculty.cs.tamu.edu/jchai/cpsc641_spring10/PerspectiveProjection.pdf)

Thanks,
Tadas

**Comment by pelingenc** [comment]
Are the 3D eye region landmarks (for pupil) equidistantly distributed?  I am trying to find the diameter of the pupils. I take the geometric mean of the 4 lengths (between the reciprocal points) to represent the pupil size. Does it make sense? How are these 8 points on the pupil calculated?
Thanks,
Pelin

**Comment by TadasBaltrusaitis** [comment]
The pupil points should be equidistantly distributed along the radius of the pupil. However, I'm not sure how accurate the pupil detection is, to be able to infer pupil size.

The 8 pupil landmarks are detected using CLNF landmark detector (more details on the algorithm and training data can be found here - https://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Wood_Rendering_of_Eyes_ICCV_2015_paper.pdf)

**Comment by TadasBaltrusaitis** [comment]
Hi, to answer your questions:
1. 3D point estimation is approximate, so there is no guarantee that fitting a circle to the points will give you a correct pupil diameter. This is because the un-projection of 2D points to 3D is under-specified problem and there is a family of solutions that can give the same answer. It is currently solved by assuming that the distance between eyes is 65mm, but this is not strictly correct for everyone.
2. You can try this out - https://meshlogic.github.io/posts/jupyter/curve-fitting/fitting-a-circle-to-cluster-of-3d-points/
3. The accuracy of the algorithm will differ slightly at different distances, also the orientation of the head is likely to have changed, affecting the accuracy again.

In general determining pupil diameter is a really difficult problem, based purely on webcam images, and I don't know if OpenFace detects pupils accurately enough for that.

**Comment by dsnsabari** [comment]
@TadasBaltrusaitis , I have predicted gaze values from the face image. How to convert that angles into real-world coordinates?
