### ISSUE TITLE
Pixel Location of extracted face in original image

### ISSUE THREAD

**Issue by zer11** [TadasBaltrusaitis/OpenFace#896]
Hey,
I'm altering the extracted faces and want to place them back into the original image.

I was looking to retrieve this information from openface but could only see pose info, but this isn't exactly what I need.
Is there a way to get the pixel location of the extracted face in the original image?

Alternatively, if anyone knows a better way to achieve what I'd like to do, please tell me

Thanks

**Comment by TadasBaltrusaitis** [comment]
What you would need to do is to "invert" the `AlignFace` call from `Face_utils.cpp`, so instead of warping from current detected landmarks to a canonical face location, you would warp from the canonical location back to the detected landmarks. So would almost be just changing source and target of the `warpAffine` call (probably a bit more complex than that, but that's the general idea)
