### ISSUE TITLE
Alternative FaceDetector

### ISSUE THREAD

**Issue by pi-null-mezon** [TadasBaltrusaitis/OpenFace#907]
It is not an issue, more couple of questions about face detection.

1) It seems that FaceDetectorMTCNN class is your own implementation of convolutional neural network. But how fast is it? Can you estimate what part (in %) of face enrollment pipeline ( frame grabbing -> face detection -> landmark detection -> AU computation) face detection costs? Cause i have found that when face moves too fast processing fps drops dramatically. Is it because face detector search iterations increase at this moment or it is something else?

2) Nowadays opencv includes its own CNN face detector that even can work on CUDA-capable devices. Is it possible to get some performance boost (in terms of fps) by replacing FaceDetectorMTCNN? Or LandmarkDetector's code is tightly coupled with FaceDetectorMTCNN?

**Comment by xkortex** [comment]
I'm likewise interested in this. 

There's what appears to be a switch which allows different facial detections, but I haven't played with the actual codebase enough to know how easy that is to modify. 

https://github.com/TadasBaltrusaitis/OpenFace/blob/master/lib/local/LandmarkDetector/src/LandmarkDetectorFunc.cpp#L314

**Comment by TadasBaltrusaitis** [comment]
It is my own implementation, it is somewhat optimized for CPU use (using OpenBLAS), but most likely does not match the most recent advances (especially on GPUs).

For processing videos face detection is only a small part of the computational cost, as it is only done when the tracking is lost. For images the cost is much higher (highly depends on resolution and number of faces in the image, so can't provide a breakdown).

> Cause i have found that when face moves too fast processing fps drops dramatically. Is it because face detector search iterations increase at this moment or it is something else?

Yes, this would be partly the impact of face re-detection and partly due to a larger ROI being used by landmark detector to make sure the face is found.

> Nowadays opencv includes its own CNN face detector that even can work on CUDA-capable devices. Is it possible to get some performance boost (in terms of fps) by replacing FaceDetectorMTCNN? Or LandmarkDetector's code is tightly coupled with FaceDetectorMTCNN?

Definitely possible, the downstream landmark detector doesn't care about underlying face detector (e.g. you can choose OpenCV HAAR, dlib, or MTCNN). One thing to be careful of is that the landmark detector needs a "tight" face bounding box that is just around the 68 landmarks (some detectors output a much wider bounding box, e.g. including forehead).

**Comment by pi-null-mezon** [comment]
Cool. Thank you)
