### ISSUE TITLE
Registered Depth

### ISSUE THREAD

**Issue by Muscio-1605187** [TadasBaltrusaitis/OpenFace#92]
Hi Tadas,
I'm using an Asus Xtion camera to get RGB and Depth images. I'm working on head pose in the project FAceLandmarkVid, in particular I'm showing the X,Y and Z coordinates that are computed in the function GetCorrectPoseCamera. Since there are to "imshow" functions that output the RGB and Depth image, my question is: are the pixels of the RGB image registered with the same pixels of the Depth image?

Thanks for your time,
Regards,
Mario

**Comment by TadasBaltrusaitis** [comment]
The system expects the depth and RGB images to be aligned, otherwise the algorithms will not work very well. I haven't used the Xtion camera so don't know if it provides them in that format, but I suspect it might.

The imshow functions display the images exactly as they acquire them from the video file or the sensor.

Thanks,
Tadas
