### ISSUE TITLE
Tracking AU 22 lip funneler

### ISSUE THREAD

**Issue by JohnboyJovi** [TadasBaltrusaitis/OpenFace#936]
Hello,

thank you for this very helpful tool. For speech articulation I would need to track also AU 22 (lip funneler) or AU 18 (lip pucker) for, e.g., o sounds. As far as I see, those are not tracked. Is there any way to do so? Or would you recommend to just estimate that myself using the facial landmarks?

I would be grateful for any recommendation.

Cheers,
Jonathan

**Comment by TadasBaltrusaitis** [comment]
Speech related action units are notoriously difficult to track (the reason they are not included in OpenFace was due to lack of training data). It might be possible to extract some information about them from landmarks, but it would be quite challenging.

If your use case involves frontal faces with good lighting and clear visibility, it might work. But if they are more unconstrained it would be challenging.

**Comment by JohnboyJovi** [comment]
Thanks a lot for your feedback and what is already there in you solution. I'll check what I can achieve.
