### ISSUE TITLE
How to use OpenFace? 

### ISSUE THREAD

**Issue by lucky2719** [TadasBaltrusaitis/OpenFace#944]
I am pretty new to this OpenFace So I would like to use open face for facial emotion prediction firstly I downloaded the tool and the gave a input of the video which gave me the csv file as output so how do I utilize this csv file for predication do I have to train my model based upon this csv file if so what are the parameters to be considered and which algorithm do u suggest?

Thank you in advance

**Comment by liang-lwk** [comment]
I have  the same  question  wanna cry

**Comment by TadasBaltrusaitis** [comment]
OpenFace is intended for facial behavior analysis, and includes features such as facial landmarks, eye gaze, head pose, and facial expression (**not** emotion). Not including emotion was an explicit design decision, as that signal is quite subjective and very context dependent. In order to do emotion recognition you would need to build something on top off or independent to OpenFace features.
