### ISSUE TITLE
HoG feature dimensionality

### ISSUE THREAD

**Issue by rubser** [TadasBaltrusaitis/OpenFace#973]
Hi,
I have extracted hog feature, through FeatureExtraction.exe, for a frame and the dimensionality is 4464. In library paper I read that, using a PCA model, the hog feature dimensionality is reduced to 1391. How can I extract the 1391 dimensionality feature? 

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Indeed, before applying SVM or SVR models the HOG feature is dimensionality reduced. However, this reduction is "folded into" the SVM computation, where we perform a single multiplication instead of two, so the dimensionality reduced PCA is never actually computed online and there is no easy way to expose it through the tool

**Comment by rubser** [comment]
Thanks for the reply. I close the topic
